### ISSUE TITLE
[RFC] Support workflow without template and configuration files

### ISSUE THREAD

**Issue by chshersh** [vaclavsvejcar/headroom#30]
I'm looking at the content of the `.headroom.yaml` file and I believe that all that information can be detected at runtime without the need to create extra configuration file. So sensible defaults would apply.

The default content of the config file:

```yaml
run-mode: add
source-paths:
  - .
template-paths:
  - headroom-templates
variables:
  author: John Smith
  email: john.smith@example.com
  project: My project
  year: '2020'
```

1. `run-mode` can be specified as a command-line argument.
2. Author and email can be guessed from the `.cabal` file (for Haskell projects, not sure about other languages)
3. Project name can be guessed from the `.cabal` file.
4. Year should be updated automatically as proposed in #29 

Or maybe you can even implement the Partial Options Monoid pattern in Haskell, so only relevant information needs to be specified in the config.
