### ISSUE TITLE
Support YAML custom settings for license headers

### ISSUE THREAD

**Issue by vaclavsvejcar** [vaclavsvejcar/headroom#32]
Right now, Headroom contains custom logic for detecting license header for each supported source code file. This logic is given and cannot be changed by any other way than by editing the source code and recompiling. Aim of this task is to add more freedom to end users to define how and mainly where should Headroom detect/render the license headers (see #28).

Example of how such configuration could look like in `.headroom.yaml`:

```yaml
license-headers:
  haskell:
    file-extensions: ["hs"]
    put-after: ["^#!"]
    starts-with: "{-"
    ends-with: "-}"
```

Such configuration for all supported languages will have default settings, so user won't have to specify this in the `.headroom.yaml` until needed.
