### ISSUE TITLE
Respect .gitignore file(s)

### ISSUE THREAD

**Issue by mheinzel** [vaclavsvejcar/headroom#42]
If there are `.gitignore` files excluding some files from the project, headroom should not touch these files (or at least provide an option not to).

This happened to me with auto-generated test files (e.g. `.stack-work/dist/x86_64-linux/Cabal-2.4.0.1/build/gundeck-tests/autogen/Paths_gundeck.hs`), which is not a big problem in this case, but might lead to very subtle issues. It also messes with timestamps.

**Comment by vaclavsvejcar** [comment]
Good idea. Personally never faced this as my `.stack-work` is outside the source directories (and in Scala/Java projects too), but this is something Headroom should support. I think as a first step, I'll implement some way how to exclude paths selected by some regex pattern (which is more general approach) and eventually in next phase implement something more VCS-specific such as extracting this info from `.gitignore` in case of GIT. Would this first (more general approach) using exclude options fit your needs?

**Comment by mheinzel** [comment]
> my `.stack-work` is outside the source directories

In our case it's a multi-package project, so we have lots of different source (and test) directories with `.stack-work` next to them.

> I think as a first step, I'll implement some way how to exclude paths selected by some regex pattern (which is more general approach)

Yes, something like `--exclude-dir ".stack-work"` would work. :+1: 

Btw, for later work on gitignore files, packages like [ignore](http://hackage.haskell.org/package/ignore) already exist.

**Comment by vaclavsvejcar** [comment]
> Btw, for later work on gitignore files, packages like [ignore](http://hackage.haskell.org/package/ignore) already exist.

Thanks for recommending this, I'll check that. I'll implement the general option to support excluding files as part of #46 and eventually keep this task for implementing the GIT-specific support for `.gitignore` files in future.

**Comment by vaclavsvejcar** [comment]
Looks that the [ignore](http://hackage.haskell.org/package/ignore) library is not being maintained for a while and causes compile errors probably due to changes in `base`, I'll check for other alternatives.

**Comment by mheinzel** [comment]
Ah, yes, it seems like it would need some work.

There's a [nice library for this in Rust](https://crates.io/crates/ignore), but if there is nothing comparable in the Haskell ecosystem, it might make sense to work on some lower hanging fruit first.

An argument for excluding source paths would certainly work for most use cases (including ours).

**Comment by vaclavsvejcar** [comment]
Hm, I think I can invest some time into this library and try to bring it back to life, after finishing all the work in progress for upcoming Headroom release 🤔

**Comment by vaclavsvejcar** [comment]
@mheinzel I just released the version [`0.2.0.0`](https://hackage.haskell.org/package/headroom-0.2.1.0) which included support for #46, guess you'd like to probably use something like

```yaml
excluded-paths:
  - '\.stack-work'
```

or some similar regex to exclude all the paths you need.

**Comment by vaclavsvejcar** [comment]
@mheinzel Hi Matthias, hope you're well 🙂 I haven't forgot about this task, just haven't had time to do it. Last few weeks, I was working on new _Haskell_ library https://github.com/vaclavsvejcar/vcs-ignore, which allows to search for and process files ignored by versioning systems. It's still work in progress, but once I'll release first public release, I plan to embed this library to _Headroom_ and implement the requested functionality. Expect it to be part of the [v0.3.3.0](https://github.com/vaclavsvejcar/headroom/milestone/10) future release. Anyway, if you'll have a while, I'd love to hear any feedback on that library.

**Comment by mheinzel** [comment]
Nice! It's quite hard to make time at the moment, but I'm interested and will try to have a look in a week or two.

**Comment by vaclavsvejcar** [comment]
Unfortunately I don't have enough time to include this to [v0.4.0.0](https://github.com/vaclavsvejcar/headroom/milestone/10) and since I don't want to block this release anymore, I postpone this for [v0.4.1.0](https://github.com/vaclavsvejcar/headroom/milestone/11) which I expect myself to release later this month.

**Comment by vaclavsvejcar** [comment]
Hello @mheinzel, I finally finished initial implementation of [vcs-ignore](https://github.com/vaclavsvejcar/vcs-ignore) library, so I was able to implement the functionality in _headroom_. It's not released yet, but you can test it with `master` branch (it's already merged). However, if you plan to test it with _Wire_, you need to use quite different configuration, because _Wire_ uses quite old version of _headroom_:

```yaml
version: 0.4.0.0
run-mode: replace
source-paths:
- libs
- services
- tools
# Exclude source paths ignored by Git
exclude-ignored-paths: true
template-paths:
- tools/headroom-templates
variables:
  organization: Wire Swiss GmbH
  email: opensource@wire.com
  project: This file is part of the Wire Server implementation.
  year: '2020'
license-headers:
  haskell:
    file-extensions: ["hs", "hsc"]
    # after pragmas, to make Ormolu happy
    put-after: ["^{-#"]
    # but before the module header (or comment) in any case
    put-before: ["^module", "^-- \\|"]
    margin-top-code: 1
    margin-bottom-code: 1
    margin-bottom-file: 1
    line-comment:
      prefixed-by: ^--
  rust:
    file-extensions: ["rs"]
    margin-top-code: 1
    margin-bottom-code: 1
    line-comment:
      prefixed-by: ^\/\/
```

I tested it and it works fine. It actually ignores some Setup.hs files, because despite present in `.gitignore`, they are already tracked and this is something that the `vcs-ignore` library cannot detect (it simply check against ignore patterns, doesn't check whether ignored files are tracked or not).
