### ISSUE TITLE
Allow template variable values to be templates itself

### ISSUE THREAD

**Issue by vaclavsvejcar** [vaclavsvejcar/headroom#51]
At this moment, values of _template variables_ are just plain strings. Goal of this task is to change this so these values can be also valid mini _Mustache_ templates, using other variables to compose their values.

#### YAML configuration
```yaml
variables:
  author: John Smith
  year: "2020"
  copyright: "(c) {{ year }} {{ author }}"
```

#### Mustache template
```mustache
{- |
Copyright:   {{ copyright }}
-}
```

#### Rendered result
```haskell
{- |
Copyright:  (c) 2020 John Smith
-}
```

This is also blocker for #29.
