### ISSUE TITLE
Use regular expressions to specify headers start/end

### ISSUE THREAD

**Issue by vaclavsvejcar** [vaclavsvejcar/headroom#61]
In current version of _Headroom_, code comments (used as _license headers_) are defined for each supported langauge either by `block-comment` or `line-comment`, like this:

```yaml
block-comment:
  starts-with: "/*"
  ends-with: "*/"
```

```yaml
line-comment:
  prefixed-by: "--"
```

where `starts-with`/`ends-with` or `prefixed-by` are plain strings specifying start and/or end of the _license header comment_. This is fine for most use cases, but the fact that these options are plain strings and not regular expressions makes it hard to do some advanced (or conditional) detection.

Goal of this task is to change this fields from plain text to regular expressions. It's breaking change, because current values, like

```yaml
block-comment:
  starts-with: "/*"
  ends-with: "*/"
```

will now need to be escaped to be valid regular expression, like this:

```yaml
block-comment:
  starts-with: ^\/\*
  ends-with: \*\/$
```
